_target_: src.models.modelmodule.OmniPoseModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.00001

scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [90, 150, 200]
  gamma: 0.1
  last_epoch: -1

net:
  _target_: src.models.components.omnipose.OmniPose

# compile model for faster training with pytorch 2.0
compile: false
